### ISSUE TITLE
Only ship LTS (even releases)?

### ISSUE THREAD

**Issue by minrk** [conda-forge/nodejs-feedstock#223]
With node's release/deprecation cadence, and the fact that LTS releases (even numbers) are "recommended for most users" should we perhaps skip odd-number releases on conda-forge?

**Comment by xhochy** [comment]
Merged 17.x before seeing this, sorry!

I would still like to build them as it still allows us to test these new versions before the next LTS.

**Comment by bollwyvl** [comment]
> skip odd-number releases on conda-forge?

YES PLEASE!

> I would still like to build them

Cool, and ship them to a `label/nodejs_not_lts`?

Or, keep them in `label/main`, but have some `nodejs-active-lts` and `nodejs-maintaince-lts` metapackages, and encourage "application" downstreams to adopt those if they otherwise don't really care about the node version (esp. `build` dependencies).

**Comment by bollwyvl** [comment]
Potentially would help: https://github.com/regro/cf-scripts/pull/1441

**Comment by minrk** [comment]
v18 later this month will put us back on LTS-on-main, so we can check back in when it's time for 19.x in October to see what our options are.

**Comment by XhstormR** [comment]
NodeJS 22 has been released.
https://nodejs.org/en/blog/announcements/v22-release-announce

**Comment by xhochy** [comment]
We're doing this now for a while. Let's close the issue.
